### ISSUE TITLE
measuring with opentype.js

### ISSUE THREAD

**Issue by devlfm** [bp74/StageXL_RichTextField#10]
This os awesome, but browsers differ from each other measuring chars.. do you think its possible to measure with opentypejs?

Thank you

**Comment by devlfm** [comment]
ping..

**Comment by bp74** [comment]
I don't like the idea to make StageXL dependent on a JavaScript library. A port of opentypejs to dart is propably a lot of work.

**Comment by devlfm** [comment]
Hmm I see your point.. thank you
