### ISSUE TITLE
Missing 'kind' field 'GraphicsGradient' class.

### ISSUE THREAD

**Issue by marcinsydor** [bp74/StageXL_RichTextField#6]
I've turned strong mode to use the lib with ddc. 
Then getting an error:
```error: The getter 'kind' isn't defined for the class 'GraphicsGradient'. (undefined_getter at [stagexl_richtextfield] lib/src/tools.dart:50)```
Not sure if it's used in my games but this issue is not let me debug them in chrome.
When I build games all work fine.

**Comment by bp74** [comment]
Okay that could be a bug. I have to activate strong mode for this library. Will do it over the weekend!

**Comment by bp74** [comment]
Hi, the problem should be fixed now. Please update your packages and give it a try.

**Comment by marcinsydor** [comment]
Thanks, I'm able to run the game in Chrome now.

**Comment by bp74** [comment]
Perfect! Thanks for the feedback.
